=== johnknl/k6-ocpi/_data/schema/generic/request.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "body": {
      "type": "object"
    },
    "headers": {
      "additionalProperties": false,
      "patternProperties": {
        "[a-z-0-9_]": {}
      },
      "properties": {
        "accept": {
          "const": "application/json"
        }
      },
      "type": "object"
    },
    "method": {
      "enum": [
        "GET",
        "POST",
        "PUT",
        "PATCH",
        "DELETE"
      ],
      "type": "string"
    },
    "url": {
      "additionalProperties": false,
      "properties": {
        "host": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "pathParams": {
          "type": "object"
        },
        "query": {
          "type": "object"
        },
        "scheme": {
          "type": "string"
        }
      },
      "required": [
        "path"
      ],
      "type": "object"
    }
  },
  "required": [
    "method",
    "url"
  ],
  "type": "object"
}

=== johnknl/k6-ocpi/_data/examples/tariffs/2.2.1/valid/receiver/request/put.json
{
  "body": {
    "country_code": "DE",
    "currency": "EUR",
    "elements": [
      {
        "price_components": [
          {
            "price": 2,
            "step_size": 300,
            "type": "TIME",
            "vat": 10
          }
        ]
      }
    ],
    "id": "12",
    "last_updated": "2024-05-31T00:00:00Z",
    "party_id": "ALL"
  },
  "headers": {
    "accept": "application/json"
  },
  "method": "PUT",
  "url": {
    "path": "/tariffs/{country_code}/{party_id}/{tariff_id}",
    "pathParams": {
      "country_code": "NL",
      "party_id": "TNM",
      "tariff_id": "12"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/locations/2.2.1/valid/receiver/request/patch.json
{
  "body": {
    "address": "F.Rooseveltlaan 3B",
    "last_updated": "2015-06-29T20:39:09Z"
  },
  "headers": {
    "accept": "application/json"
  },
  "method": "PATCH",
  "url": {
    "path": "/locations/{country_code}/{party_id}/{location_id}",
    "pathParams": {
      "country_code": "NL",
      "location_id": "12",
      "party_id": "TNM"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/locations/2.1.1/valid/receiver/request/patch.connector.json
{
  "body": {
    "tariff_id": "15"
  },
  "headers": {
    "accept": "application/json"
  },
  "method": "PATCH",
  "url": {
    "path": "/locations/{country_code}/{party_id}/{location_id}/{evse_uid}/{connector_id}",
    "pathParams": {
      "connector_id": "1",
      "country_code": "NL",
      "evse_uid": "3256",
      "location_id": "12",
      "party_id": "TNM"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/locations/2.1.1/valid/receiver/request/remove-evse.json
{
  "body": {
    "status": "REMOVED"
  },
  "headers": {
    "accept": "application/json"
  },
  "method": "PATCH",
  "url": {
    "path": "/locations/{country_code}/{party_id}/{location_id}/{evse_uid}",
    "pathParams": {
      "country_code": "NL",
      "evse_uid": "3257",
      "location_id": "12",
      "party_id": "TNM"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/locations/2.2.1/valid/receiver/request/put.evse.json
{
  "body": {
    "capabilities": [
      "RESERVABLE"
    ],
    "connectors": [
      {
        "format": "SOCKET",
        "id": "1",
        "last_updated": "2015-06-29T20:39:09Z",
        "max_amperage": 16,
        "max_voltage": 220,
        "power_type": "AC_3_PHASE",
        "standard": "IEC_62196_T2",
        "tariff_ids": [
          "12"
        ]
      }
    ],
    "evse_id": "BE*BEC*E041503002",
    "floor_level": "-2",
    "last_updated": "2015-06-29T20:39:09Z",
    "physical_reference": "2",
    "status": "AVAILABLE",
    "uid": "3257"
  },
  "headers": {
    "accept": "application/json"
  },
  "method": "PUT",
  "url": {
    "path": "/locations/{country_code}/{party_id}/{location_id}/{evse_uid}",
    "pathParams": {
      "country_code": "NL",
      "evse_uid": "3257",
      "location_id": "12",
      "party_id": "TNM"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/locations/2.1.1/valid/receiver/request/put.connector.json
{
  "body": {
    "amperage": 16,
    "format": "SOCKET",
    "id": "1",
    "last_updated": "2015-06-29T20:39:09Z",
    "power_type": "AC_3_PHASE",
    "standard": "IEC_62196_T2",
    "voltage": 220
  },
  "headers": {
    "accept": "application/json"
  },
  "method": "PUT",
  "url": {
    "path": "/locations/{country_code}/{party_id}/{location_id}/{evse_uid}/{connector_id}",
    "pathParams": {
      "connector_id": "1",
      "country_code": "NL",
      "evse_uid": "3257",
      "location_id": "12",
      "party_id": "TNM"
    }
  }
}
