=== johnknl/k6-ocpi/_data/schema/generated/ocpi.2_1_1.evse.json
{
  "$ref": "#/definitions/ocpi.2_1_1.evse",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ocpi.2_1_1.evse": {
      "additionalProperties": false,
      "properties": {
        "capabilities": {
          "anyOf": [
            {
              "items": {
                "enum": [
                  "CHARGING_PROFILE_CAPABLE",
                  "CREDIT_CARD_PAYABLE",
                  "REMOTE_START_STOP_CAPABLE",
                  "RESERVABLE",
                  "RFID_READER",
                  "UNLOCK_CAPABLE"
                ],
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "connectors": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "amperage": {
                "type": "integer"
              },
              "format": {
                "enum": [
                  "SOCKET",
                  "CABLE"
                ],
                "type": "string"
              },
              "id": {
                "maxLength": 36,
                "type": "string"
              },
              "last_updated": {
                "format": "date-time",
                "type": "string"
              },
              "power_type": {
                "enum": [
                  "AC_1_PHASE",
                  "AC_3_PHASE",
                  "DC"
                ],
                "type": "string"
              },
              "standard": {
                "enum": [
                  "CHADEMO",
                  "DOMESTIC_A",
                  "DOMESTIC_B",
                  "DOMESTIC_C",
                  "DOMESTIC_D",
                  "DOMESTIC_E",
                  "DOMESTIC_F",
                  "DOMESTIC_G",
                  "DOMESTIC_H",
                  "DOMESTIC_I",
                  "DOMESTIC_J",
                  "DOMESTIC_K",
                  "DOMESTIC_L",
                  "IEC_60309_2_single_16",
                  "IEC_60309_2_three_16",
                  "IEC_60309_2_three_32",
                  "IEC_60309_2_three_64",
                  "IEC_62196_T1",
                  "IEC_62196_T1_COMBO",
                  "IEC_62196_T2",
                  "IEC_62196_T2_COMBO",
                  "IEC_62196_T3A",
                  "IEC_62196_T3C",
                  "TESLA_R",
                  "TESLA_S"
                ],
                "type": "string"
              },
              "tariff_id": {
                "anyOf": [
                  {
                    "maxLength": 36,
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "terms_and_conditions": {
                "anyOf": [
                  {
                    "format": "uri",
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "voltage": {
                "type": "integer"
              }
            },
            "required": [
              "id",
              "standard",
              "format",
              "power_type",
              "voltage",
              "amperage",
              "last_updated"
            ],
            "type": "object"
          },
          "minItems": 1,
          "type": "array"
        },
        "coordinates": {
          "anyOf": [
            {
              "additionalProperties": false,
              "properties": {
                "latitude": {
                  "maxLength": 10,
                  "pattern": "-?[0-9]{1,2}\\.[0-9]{6}",
                  "type": "string"
                },
                "longitude": {
                  "maxLength": 11,
                  "pattern": "-?[0-9]{1,3}\\.[0-9]{6}",
                  "type": "string"
                }
              },
              "required": [
                "latitude",
                "longitude"
              ],
              "type": "object"
            },
            {
              "type": "null"
            }
          ]
        },
        "directions": {
          "anyOf": [
            {
              "items": {
                "additionalProperties": false,
                "properties": {
                  "language": {
                    "maxLength": 2,
                    "minLength": 2,
                    "type": "string"
                  },
                  "text": {
                    "maxLength": 512,
                    "type": "string"
                  }
                },
                "required": [
                  "language",
                  "text"
                ],
                "type": "object"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "evse_id": {
          "anyOf": [
            {
              "maxLength": 48,
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "floor_level": {
          "anyOf": [
            {
              "maxLength": 4,
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "images": {
          "anyOf": [
            {
              "items": {
                "additionalProperties": false,
                "properties": {
                  "category": {
                    "enum": [
                      "CHARGER",
                      "ENTRANCE",
                      "LOCATION",
                      "NETWORK",
                      "OPERATOR",
                      "OTHER",
                      "OWNER"
                    ],
                    "type": "string"
                  },
                  "height": {
                    "anyOf": [
                      {
                        "maximum": 99999,
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "thumbnail": {
                    "anyOf": [
                      {
                        "format": "uri",
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "type": {
                    "maxLength": 4,
                    "type": "string"
                  },
                  "url": {
                    "format": "uri",
                    "type": "string"
                  },
                  "width": {
                    "anyOf": [
                      {
                        "maximum": 99999,
                        "type": "integer"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "url",
                  "category",
                  "type"
                ],
                "type": "object"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "last_updated": {
          "format": "date-time",
          "type": "string"
        },
        "parking_restrictions": {
          "anyOf": [
            {
              "items": {
                "enum": [
                  "EV_ONLY",
                  "PLUGGED",
                  "DISABLED",
                  "CUSTOMERS",
                  "MOTORCYCLES"
                ],
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "physical_reference": {
          "anyOf": [
            {
              "maxLength": 16,
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "status": {
          "enum": [
            "AVAILABLE",
            "BLOCKED",
            "CHARGING",
            "INOPERATIVE",
            "OUTOFORDER",
            "PLANNED",
            "REMOVED",
            "RESERVED",
            "UNKNOWN"
          ],
          "type": "string"
        },
        "status_schedule": {
          "anyOf": [
            {
              "items": {
                "additionalProperties": false,
                "properties": {
                  "period_begin": {
                    "format": "date-time",
                    "type": "string"
                  },
                  "period_end": {
                    "anyOf": [
                      {
                        "format": "date-time",
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "status": {
                    "$ref": "#/definitions/ocpi.2_1_1.evse/properties/status"
                  }
                },
                "required": [
                  "period_begin",
                  "status"
                ],
                "type": "object"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "uid": {
          "maxLength": 39,
          "type": "string"
        }
      },
      "required": [
        "uid",
        "status",
        "connectors",
        "last_updated"
      ],
      "type": "object"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/locations/2.1.1/valid/_examples/evse.json
{
  "capabilities": [
    "RESERVABLE"
  ],
  "connectors": [
    {
      "amperage": 16,
      "format": "SOCKET",
      "id": "1",
      "last_updated": "2015-06-29T20:39:09Z",
      "power_type": "AC_3_PHASE",
      "standard": "IEC_62196_T2",
      "tariff_id": "14",
      "voltage": 220
    }
  ],
  "evse_id": "BE-BEC-E041503003",
  "floor_level": "-1",
  "last_updated": "2015-06-29T20:39:09Z",
  "physical_reference": "3",
  "status": "AVAILABLE",
  "uid": "3256"
}
