=== johnknl/k6-ocpi/_data/schema/ocpi/locations/ocpi.2_2_1.location.json
{
  "$ref": "#/definitions/Location",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AdditionalGeoLocation": {
      "additionalProperties": false,
      "properties": {
        "latitude": {
          "maxLength": 10,
          "pattern": "-?[0-9]{1,2}\\.[0-9]{5,7}",
          "type": "string"
        },
        "longitude": {
          "maxLength": 11,
          "pattern": "-?[0-9]{1,3}\\.[0-9]{5,7}",
          "type": "string"
        },
        "name": {
          "anyOf": [
            {
              "$ref": "#/definitions/DisplayText"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "latitude",
        "longitude"
      ],
      "type": "object"
    },
    "BusinessDetails": {
      "additionalProperties": false,
      "properties": {
        "logo": {
          "anyOf": [
            {
              "$ref": "#/definitions/Image"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "maxLength": 100,
          "type": "string"
        },
        "website": {
          "format": "uri",
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "name"
      ],
      "type": "object"
    },
    "Capability": {
      "enum": [
        "CHARGING_PROFILE_CAPABLE",
        "CHARGING_PREFERENCES_CAPABLE",
        "CHIP_CARD_SUPPORT",
        "CONTACTLESS_CARD_SUPPORT",
        "CREDIT_CARD_PAYABLE",
        "DEBIT_CARD_PAYABLE",
        "PED_TERMINAL",
        "REMOTE_START_STOP_CAPABLE",
        "RESERVABLE",
        "RFID_READER",
        "START_SESSION_CONNECTOR_REQUIRED",
        "TOKEN_GROUP_CAPABLE",
        "UNLOCK_CAPABLE"
      ],
      "type": "string"
    },
    "Connector": {
      "additionalProperties": false,
      "properties": {
        "format": {
          "$ref": "#/definitions/ConnectorFormat"
        },
        "id": {
          "maxLength": 36,
          "type": "string"
        },
        "last_updated": {
          "format": "date-time",
          "type": "string"
        },
        "max_amperage": {
          "type": "integer"
        },
        "max_electric_power": {
          "type": [
            "null",
            "integer"
          ]
        },
        "max_voltage": {
          "type": "integer"
        },
        "power_type": {
          "$ref": "#/definitions/PowerType"
        },
        "standard": {
          "$ref": "#/definitions/ConnectorType"
        },
        "tariff_ids": {
          "items": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "anyOf": [
                  {
                    "maxLength": 36,
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            ]
          },
          "type": [
            "null",
            "array"
          ]
        },
        "terms_and_conditions": {
          "format": "uri",
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "id",
        "standard",
        "format",
        "power_type",
        "max_voltage",
        "max_amperage",
        "last_updated"
      ],
      "type": "object"
    },
    "ConnectorFormat": {
      "enum": [
        "SOCKET",
        "CABLE"
      ],
      "type": "string"
    },
    "ConnectorType": {
      "enum": [
        "CHADEMO",
        "CHAOJI",
        "DOMESTIC_A",
        "DOMESTIC_B",
        "DOMESTIC_C",
        "DOMESTIC_D",
        "DOMESTIC_E",
        "DOMESTIC_F",
        "DOMESTIC_G",
        "DOMESTIC_H",
        "DOMESTIC_I",
        "DOMESTIC_J",
        "DOMESTIC_K",
        "DOMESTIC_L",
        "DOMESTIC_M",
        "DOMESTIC_N",
        "DOMESTIC_O",
        "GBT_AC",
        "GBT_DC",
        "IEC_60309_2_single_16",
        "IEC_60309_2_three_16",
        "IEC_60309_2_three_32",
        "IEC_60309_2_three_64",
        "IEC_62196_T1",
        "IEC_62196_T1_COMBO",
        "IEC_62196_T2",
        "IEC_62196_T2_COMBO",
        "IEC_62196_T3A",
        "IEC_62196_T3C",
        "NEMA_5_20",
        "NEMA_6_30",
        "NEMA_6_50",
        "NEMA_10_30",
        "NEMA_10_50",
        "NEMA_14_30",
        "NEMA_14_50",
        "PANTOGRAPH_BOTTOM_UP",
        "PANTOGRAPH_TOP_DOWN",
        "TESLA_R",
        "TESLA_S"
      ],
      "type": "string"
    },
    "DisplayText": {
      "additionalProperties": false,
      "properties": {
        "language": {
          "maxLength": 2,
          "minLength": 2,
          "type": "string"
        },
        "text": {
          "maxLength": 512,
          "type": "string"
        }
      },
      "required": [
        "language",
        "text"
      ],
      "type": "object"
    },
    "EVSE": {
      "additionalProperties": false,
      "properties": {
        "capabilities": {
          "items": {
            "$ref": "#/definitions/Capability"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "connectors": {
          "items": {
            "$ref": "#/definitions/Connector"
          },
          "minItems": 1,
          "type": "array"
        },
        "coordinates": {
          "anyOf": [
            {
              "$ref": "#/definitions/GeoLocation"
            },
            {
              "type": "null"
            }
          ]
        },
        "directions": {
          "items": {
            "$ref": "#/definitions/DisplayText"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "evse_id": {
          "maxLength": 48,
          "type": [
            "null",
            "string"
          ]
        },
        "floor_level": {
          "maxLength": 4,
          "type": [
            "null",
            "string"
          ]
        },
        "images": {
          "items": {
            "$ref": "#/definitions/Image"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "last_updated": {
          "format": "date-time",
          "type": "string"
        },
        "parking_restrictions": {
          "items": {
            "$ref": "#/definitions/ParkingRestriction"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "physical_reference": {
          "maxLength": 16,
          "type": [
            "null",
            "string"
          ]
        },
        "status": {
          "$ref": "#/definitions/Status"
        },
        "status_schedule": {
          "items": {
            "$ref": "#/definitions/StatusSchedule"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "uid": {
          "maxLength": 39,
          "type": "string"
        }
      },
      "required": [
        "uid",
        "status",
        "connectors",
        "last_updated"
      ],
      "type": "object"
    },
    "EnergyMix": {
      "additionalProperties": false,
      "properties": {
        "energy_product_name": {
          "maxLength": 64,
          "type": [
            "null",
            "string"
          ]
        },
        "energy_sources": {
          "items": {
            "$ref": "#/definitions/EnergySource"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "environ_impact": {
          "items": {
            "$ref": "#/definitions/EnvironmentalImpact"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "is_green_energy": {
          "type": "boolean"
        },
        "supplier_name": {
          "maxLength": 64,
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "is_green_energy"
      ],
      "type": "object"
    },
    "EnergySource": {
      "additionalProperties": false,
      "properties": {
        "percentage": {
          "maximum": 100,
          "minimum": 0,
          "type": "number"
        },
        "source": {
          "$ref": "#/definitions/EnergySourceCategory"
        }
      },
      "required": [
        "source",
        "percentage"
      ],
      "type": "object"
    },
    "EnergySourceCategory": {
      "enum": [
        "NUCLEAR",
        "GENERAL_FOSSIL",
        "COAL",
        "GAS",
        "GENERAL_GREEN",
        "SOLAR",
        "WIND",
        "WATER"
      ],
      "type": "string"
    },
    "EnvironmentalImpact": {
      "additionalProperties": false,
      "properties": {
        "amount": {
          "type": "number"
        },
        "category": {
          "$ref": "#/definitions/EnvironmentalImpactCategory"
        }
      },
      "required": [
        "source",
        "amount"
      ],
      "type": "object"
    },
    "EnvironmentalImpactCategory": {
      "enum": [
        "NUCLEAR_WASTE",
        "CARBON_DIOXIDE"
      ],
      "type": "string"
    },
    "ExceptionalPeriod": {
      "additionalProperties": false,
      "properties": {
        "period_begin": {
          "format": "date-time",
          "type": "string"
        },
        "period_end": {
          "format": "date-time",
          "type": "string"
        }
      },
      "required": [
        "period_begin",
        "period_end"
      ],
      "type": "object"
    },
    "Facility": {
      "enum": [
        "HOTEL",
        "RESTAURANT",
        "CAFE",
        "MALL",
        "SUPERMARKET",
        "SPORT",
        "RECREATION_AREA",
        "NATURE",
        "MUSEUM",
        "BIKE_SHARING",
        "BUS_STOP",
        "TAXI_STAND",
        "TRAM_STOP",
        "METRO_STATION",
        "TRAIN_STATION",
        "AIRPORT",
        "PARKING_LOT",
        "CARPOOL_PARKING",
        "FUEL_STATION",
        "WIFI"
      ],
      "type": "string"
    },
    "GeoLocation": {
      "additionalProperties": false,
      "properties": {
        "latitude": {
          "maxLength": 10,
          "pattern": "-?[0-9]{1,2}\\.[0-9]{5,7}",
          "type": "string"
        },
        "longitude": {
          "maxLength": 11,
          "pattern": "-?[0-9]{1,3}\\.[0-9]{5,7}",
          "type": "string"
        }
      },
      "required": [
        "latitude",
        "longitude"
      ],
      "type": "object"
    },
    "Hours": {
      "additionalProperties": false,
      "properties": {
        "exceptional_closings": {
          "items": {
            "$ref": "#/definitions/ExceptionalPeriod"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "exceptional_openings": {
          "items": {
            "$ref": "#/definitions/ExceptionalPeriod"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "regular_hours": {
          "items": {
            "$ref": "#/definitions/RegularHours"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "twentyfourseven": {
          "type": "boolean"
        }
      },
      "required": [
        "twentyfourseven"
      ],
      "type": "object"
    },
    "Image": {
      "additionalProperties": false,
      "properties": {
        "category": {
          "enum": [
            "CHARGER",
            "ENTRANCE",
            "LOCATION",
            "NETWORK",
            "OPERATOR",
            "OTHER",
            "OWNER"
          ],
          "type": "string"
        },
        "height": {
          "maximum": 99999,
          "type": [
            "null",
            "integer"
          ]
        },
        "thumbnail": {
          "format": "uri",
          "type": [
            "null",
            "string"
          ]
        },
        "type": {
          "maxLength": 4,
          "type": "string"
        },
        "url": {
          "format": "uri",
          "type": "string"
        },
        "width": {
          "maximum": 99999,
          "type": [
            "null",
            "integer"
          ]
        }
      },
      "required": [
        "url",
        "category",
        "type"
      ],
      "type": "object"
    },
    "Location": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "maxLength": 45,
          "type": "string"
        },
        "charging_when_closed": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "city": {
          "maxLength": 45,
          "type": "string"
        },
        "coordinates": {
          "$ref": "#/definitions/GeoLocation"
        },
        "country": {
          "maxLength": 3,
          "minLength": 3,
          "type": "string"
        },
        "country_code": {
          "maxLength": 2,
          "minLength": 2,
          "type": "string"
        },
        "directions": {
          "items": {
            "$ref": "#/definitions/DisplayText"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "energy_mix": {
          "anyOf": [
            {
              "$ref": "#/definitions/EnergyMix"
            },
            {
              "type": "null"
            }
          ]
        },
        "evses": {
          "items": {
            "$ref": "#/definitions/EVSE"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "facilities": {
          "items": {
            "$ref": "#/definitions/Facility"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "id": {
          "maxLength": 36,
          "type": "string"
        },
        "images": {
          "items": {
            "$ref": "#/definitions/Image"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "last_updated": {
          "format": "date-time",
          "type": "string"
        },
        "name": {
          "maxLength": 255,
          "type": [
            "null",
            "string"
          ]
        },
        "opening_times": {
          "anyOf": [
            {
              "$ref": "#/definitions/Hours"
            },
            {
              "type": "null"
            }
          ]
        },
        "operator": {
          "anyOf": [
            {
              "$ref": "#/definitions/BusinessDetails"
            },
            {
              "type": "null"
            }
          ]
        },
        "owner": {
          "anyOf": [
            {
              "$ref": "#/definitions/BusinessDetails"
            },
            {
              "type": "null"
            }
          ]
        },
        "parking_type": {
          "anyOf": [
            {
              "$ref": "#/definitions/ParkingType"
            },
            {
              "type": "null"
            }
          ]
        },
        "party_id": {
          "maxLength": 3,
          "type": "string"
        },
        "postal_code": {
          "maxLength": 10,
          "type": [
            "null",
            "string"
          ]
        },
        "publish": {
          "type": "boolean"
        },
        "publish_allowed_to": {
          "items": {
            "$ref": "#/definitions/PublishTokenType"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "related_locations": {
          "items": {
            "$ref": "#/definitions/AdditionalGeoLocation"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "state": {
          "maxLength": 20,
          "type": [
            "null",
            "string"
          ]
        },
        "suboperator": {
          "anyOf": [
            {
              "$ref": "#/definitions/BusinessDetails"
            },
            {
              "type": "null"
            }
          ]
        },
        "time_zone": {
          "maxLength": 255,
          "type": "string"
        }
      },
      "required": [
        "country_code",
        "party_id",
        "id",
        "publish",
        "address",
        "city",
        "country",
        "coordinates",
        "time_zone",
        "last_updated"
      ],
      "type": "object"
    },
    "ParkingRestriction": {
      "enum": [
        "EV_ONLY",
        "PLUGGED",
        "DISABLED",
        "CUSTOMERS",
        "MOTORCYCLES"
      ],
      "type": "string"
    },
    "ParkingType": {
      "enum": [
        "ALONG_MOTORWAY",
        "ON_STREET",
        "ON_DRIVEWAY",
        "PARKING_GARAGE",
        "UNDERGROUND_GARAGE",
        "PARKING_LOT"
      ],
      "type": "string"
    },
    "PowerType": {
      "enum": [
        "AC_1_PHASE",
        "AC_2_PHASE",
        "AC_2_PHASE_SPLIT",
        "AC_3_PHASE",
        "DC"
      ],
      "type": "string"
    },
    "PublishTokenType": {
      "additionalProperties": false,
      "properties": {
        "group_id": {
          "maxLength": 36,
          "type": [
            "null",
            "string"
          ]
        },
        "issuer": {
          "maxLength": 64,
          "type": [
            "null",
            "string"
          ]
        },
        "type": {
          "enum": [
            "AD_HOC_USER",
            "APP_USER",
            "OTHER",
            "RFID"
          ],
          "type": [
            "null",
            "string"
          ]
        },
        "uid": {
          "maxLength": 36,
          "type": [
            "null",
            "string"
          ]
        },
        "visual_number": {
          "maxLength": 64,
          "type": [
            "null",
            "string"
          ]
        }
      },
      "type": "object"
    },
    "RegularHours": {
      "additionalProperties": false,
      "properties": {
        "period_begin": {
          "maxLength": 5,
          "minLength": 5,
          "pattern": "([0-1][0-9]|2[0-3]):[0-5][0-9]",
          "type": "string"
        },
        "period_end": {
          "maxLength": 5,
          "minLength": 5,
          "pattern": "([0-1][0-9]|2[0-3]):[0-5][0-9]",
          "type": "string"
        },
        "weekday": {
          "maximum": 7,
          "minimum": 1,
          "type": "integer"
        }
      },
      "required": [
        "weekday",
        "period_begin",
        "period_end"
      ],
      "type": "object"
    },
    "Status": {
      "enum": [
        "AVAILABLE",
        "BLOCKED",
        "CHARGING",
        "INOPERATIVE",
        "OUTOFORDER",
        "PLANNED",
        "REMOVED",
        "RESERVED",
        "UNKNOWN"
      ],
      "type": "string"
    },
    "StatusSchedule": {
      "additionalProperties": false,
      "properties": {
        "period_begin": {
          "format": "date-time",
          "type": "string"
        },
        "period_end": {
          "format": "date-time",
          "type": [
            "null",
            "string"
          ]
        },
        "status": {
          "enum": [
            "AVAILABLE",
            "BLOCKED",
            "CHARGING",
            "INOPERATIVE",
            "OUTOFORDER",
            "PLANNED",
            "REMOVED",
            "RESERVED",
            "UNKNOWN"
          ],
          "type": "string"
        }
      },
      "required": [
        "period_begin",
        "period_end",
        "status"
      ],
      "type": "object"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/locations/2.2.1/valid/_examples/location.json
{
  "address": "F.Rooseveltlaan 3A",
  "city": "Gent",
  "coordinates": {
    "latitude": "51.047599",
    "longitude": "3.729944"
  },
  "country": "BEL",
  "country_code": "BE",
  "evses": [
    {
      "capabilities": [
        "RESERVABLE"
      ],
      "connectors": [
        {
          "format": "CABLE",
          "id": "1",
          "last_updated": "2015-03-16T10:10:02Z",
          "max_amperage": 16,
          "max_voltage": 220,
          "power_type": "AC_3_PHASE",
          "standard": "IEC_62196_T2",
          "tariff_ids": [
            "11"
          ]
        },
        {
          "format": "SOCKET",
          "id": "2",
          "last_updated": "2015-03-18T08:12:01Z",
          "max_amperage": 16,
          "max_voltage": 220,
          "power_type": "AC_3_PHASE",
          "standard": "IEC_62196_T2",
          "tariff_ids": [
            "13"
          ]
        }
      ],
      "evse_id": "BE*BEC*E041503001",
      "floor_level": "-1",
      "last_updated": "2015-06-28T08:12:01Z",
      "physical_reference": "1",
      "status": "AVAILABLE",
      "uid": "3256"
    },
    {
      "capabilities": [
        "RESERVABLE"
      ],
      "connectors": [
        {
          "format": "SOCKET",
          "id": "1",
          "last_updated": "2015-06-29T20:39:09Z",
          "max_amperage": 16,
          "max_voltage": 220,
          "power_type": "AC_3_PHASE",
          "standard": "IEC_62196_T2",
          "tariff_ids": [
            "12"
          ]
        }
      ],
      "evse_id": "BE*BEC*E041503002",
      "floor_level": "-2",
      "last_updated": "2015-06-29T20:39:09Z",
      "physical_reference": "2",
      "status": "RESERVED",
      "uid": "3257"
    }
  ],
  "id": "LOC1",
  "last_updated": "2015-06-29T20:39:09Z",
  "name": "Gent Zuid",
  "operator": {
    "name": "BeCharged"
  },
  "parking_type": "ON_STREET",
  "party_id": "BEC",
  "postal_code": "9000",
  "publish": true,
  "time_zone": "Europe/Brussels"
}
