=== johnknl/k6-ocpi/_data/schema/ocpi/locations/ocpi.2_1_1.location.json
{
  "$ref": "#/definitions/Location",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AdditionalGeoLocation": {
      "additionalProperties": false,
      "properties": {
        "latitude": {
          "maxLength": 10,
          "pattern": "-?[0-9]{1,2}\\.[0-9]{6}",
          "type": "string"
        },
        "longitude": {
          "maxLength": 11,
          "pattern": "-?[0-9]{1,3}\\.[0-9]{6}",
          "type": "string"
        },
        "name": {
          "additionalProperties": false,
          "properties": {
            "language": {
              "maxLength": 2,
              "minLength": 2,
              "type": "string"
            },
            "text": {
              "maxLength": 512,
              "type": "string"
            }
          },
          "required": [
            "language",
            "text"
          ],
          "type": [
            "null",
            "object"
          ]
        }
      },
      "required": [
        "latitude",
        "longitude"
      ],
      "type": "object"
    },
    "BusinessDetails": {
      "additionalProperties": false,
      "properties": {
        "logo": {
          "additionalProperties": false,
          "properties": {
            "category": {
              "enum": [
                "CHARGER",
                "ENTRANCE",
                "LOCATION",
                "NETWORK",
                "OPERATOR",
                "OTHER",
                "OWNER"
              ],
              "type": "string"
            },
            "height": {
              "maximum": 99999,
              "type": [
                "null",
                "integer"
              ]
            },
            "thumbnail": {
              "format": "uri",
              "type": [
                "null",
                "string"
              ]
            },
            "type": {
              "maxLength": 4,
              "type": "string"
            },
            "url": {
              "format": "uri",
              "type": "string"
            },
            "width": {
              "maximum": 99999,
              "type": [
                "null",
                "integer"
              ]
            }
          },
          "required": [
            "url",
            "category",
            "type"
          ],
          "type": [
            "null",
            "object"
          ]
        },
        "name": {
          "maxLength": 100,
          "type": "string"
        },
        "website": {
          "format": "uri",
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "name"
      ],
      "type": "object"
    },
    "Capability": {
      "enum": [
        "CHARGING_PROFILE_CAPABLE",
        "CREDIT_CARD_PAYABLE",
        "REMOTE_START_STOP_CAPABLE",
        "RESERVABLE",
        "RFID_READER",
        "UNLOCK_CAPABLE"
      ],
      "type": "string"
    },
    "Connector": {
      "additionalProperties": false,
      "properties": {
        "amperage": {
          "type": "integer"
        },
        "format": {
          "enum": [
            "SOCKET",
            "CABLE"
          ],
          "type": "string"
        },
        "id": {
          "maxLength": 36,
          "type": "string"
        },
        "last_updated": {
          "format": "date-time",
          "type": "string"
        },
        "power_type": {
          "enum": [
            "AC_1_PHASE",
            "AC_3_PHASE",
            "DC"
          ],
          "type": "string"
        },
        "standard": {
          "enum": [
            "CHADEMO",
            "DOMESTIC_A",
            "DOMESTIC_B",
            "DOMESTIC_C",
            "DOMESTIC_D",
            "DOMESTIC_E",
            "DOMESTIC_F",
            "DOMESTIC_G",
            "DOMESTIC_H",
            "DOMESTIC_I",
            "DOMESTIC_J",
            "DOMESTIC_K",
            "DOMESTIC_L",
            "IEC_60309_2_single_16",
            "IEC_60309_2_three_16",
            "IEC_60309_2_three_32",
            "IEC_60309_2_three_64",
            "IEC_62196_T1",
            "IEC_62196_T1_COMBO",
            "IEC_62196_T2",
            "IEC_62196_T2_COMBO",
            "IEC_62196_T3A",
            "IEC_62196_T3C",
            "TESLA_R",
            "TESLA_S"
          ],
          "type": "string"
        },
        "tariff_id": {
          "maxLength": 36,
          "type": [
            "null",
            "string"
          ]
        },
        "terms_and_conditions": {
          "format": "uri",
          "type": [
            "null",
            "string"
          ]
        },
        "voltage": {
          "type": "integer"
        }
      },
      "required": [
        "id",
        "standard",
        "format",
        "power_type",
        "voltage",
        "amperage",
        "last_updated"
      ],
      "type": "object"
    },
    "DisplayText": {
      "additionalProperties": false,
      "properties": {
        "language": {
          "maxLength": 2,
          "minLength": 2,
          "type": "string"
        },
        "text": {
          "maxLength": 512,
          "type": "string"
        }
      },
      "required": [
        "language",
        "text"
      ],
      "type": [
        "null",
        "object"
      ]
    },
    "EVSE": {
      "additionalProperties": false,
      "properties": {
        "capabilities": {
          "items": {
            "$ref": "#/definitions/Capability"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "connectors": {
          "items": {
            "$ref": "#/definitions/Connector"
          },
          "minItems": 1,
          "type": "array"
        },
        "coordinates": {
          "anyOf": [
            {
              "$ref": "#/definitions/GeoLocation"
            },
            {
              "type": "null"
            }
          ]
        },
        "directions": {
          "items": {
            "$ref": "#/definitions/DisplayText"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "evse_id": {
          "maxLength": 48,
          "type": [
            "null",
            "string"
          ]
        },
        "floor_level": {
          "maxLength": 4,
          "type": [
            "null",
            "string"
          ]
        },
        "images": {
          "items": {
            "$ref": "#/definitions/Image"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "last_updated": {
          "format": "date-time",
          "type": "string"
        },
        "parking_restrictions": {
          "items": {
            "$ref": "#/definitions/ParkingRestriction"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "physical_reference": {
          "maxLength": 16,
          "type": [
            "null",
            "string"
          ]
        },
        "status": {
          "$ref": "#/definitions/Status"
        },
        "status_schedule": {
          "items": {
            "$ref": "#/definitions/StatusSchedule"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "uid": {
          "maxLength": 39,
          "type": "string"
        }
      },
      "required": [
        "uid",
        "status",
        "connectors",
        "last_updated"
      ],
      "type": "object"
    },
    "EnergyMix": {
      "additionalProperties": false,
      "properties": {
        "energy_product_name": {
          "maxLength": 64,
          "type": [
            "null",
            "string"
          ]
        },
        "energy_sources": {
          "items": {
            "$ref": "#/definitions/EnergySource"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "environ_impact": {
          "items": {
            "$ref": "#/definitions/EnvironmentalImpact"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "is_green_energy": {
          "type": "boolean"
        },
        "supplier_name": {
          "maxLength": 64,
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "is_green_energy"
      ],
      "type": "object"
    },
    "EnergySource": {
      "additionalProperties": false,
      "properties": {
        "percentage": {
          "maximum": 100,
          "minimum": 0,
          "type": "number"
        },
        "source": {
          "$ref": "#/definitions/EnergySourceCategory"
        }
      },
      "required": [
        "source",
        "percentage"
      ],
      "type": "object"
    },
    "EnergySourceCategory": {
      "enum": [
        "NUCLEAR",
        "GENERAL_FOSSIL",
        "COAL",
        "GAS",
        "GENERAL_GREEN",
        "SOLAR",
        "WIND",
        "WATER"
      ],
      "type": "string"
    },
    "EnvironmentalImpact": {
      "additionalProperties": false,
      "properties": {
        "amount": {
          "type": "number"
        },
        "source": {
          "$ref": "#/definitions/EnvironmentalImpactCategory"
        }
      },
      "required": [
        "source",
        "amount"
      ],
      "type": "object"
    },
    "EnvironmentalImpactCategory": {
      "enum": [
        "NUCLEAR_WASTE",
        "CARBON_DIOXIDE"
      ],
      "type": "string"
    },
    "ExceptionalPeriod": {
      "additionalProperties": false,
      "properties": {
        "period_begin": {
          "format": "date-time",
          "type": "string"
        },
        "period_end": {
          "format": "date-time",
          "type": "string"
        }
      },
      "required": [
        "period_begin",
        "period_end"
      ],
      "type": "object"
    },
    "Facility": {
      "enum": [
        "HOTEL",
        "RESTAURANT",
        "CAFE",
        "MALL",
        "SUPERMARKET",
        "SPORT",
        "RECREATION_AREA",
        "NATURE",
        "MUSEUM",
        "BUS_STOP",
        "TAXI_STAND",
        "TRAIN_STATION",
        "AIRPORT",
        "CARPOOL_PARKING",
        "FUEL_STATION",
        "WIFI"
      ],
      "type": "string"
    },
    "GeoLocation": {
      "additionalProperties": false,
      "properties": {
        "latitude": {
          "maxLength": 10,
          "pattern": "-?[0-9]{1,2}\\.[0-9]{6}",
          "type": "string"
        },
        "longitude": {
          "maxLength": 11,
          "pattern": "-?[0-9]{1,3}\\.[0-9]{6}",
          "type": "string"
        }
      },
      "required": [
        "latitude",
        "longitude"
      ],
      "type": "object"
    },
    "Hours": {
      "additionalProperties": false,
      "properties": {
        "exceptional_closings": {
          "items": {
            "$ref": "#/definitions/ExceptionalPeriod"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "exceptional_openings": {
          "items": {
            "$ref": "#/definitions/ExceptionalPeriod"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "regular_hours": {
          "items": {
            "$ref": "#/definitions/RegularHours"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "twentyfourseven": {
          "type": "boolean"
        }
      },
      "required": [
        "twentyfourseven"
      ],
      "type": "object"
    },
    "Image": {
      "additionalProperties": false,
      "properties": {
        "category": {
          "enum": [
            "CHARGER",
            "ENTRANCE",
            "LOCATION",
            "NETWORK",
            "OPERATOR",
            "OTHER",
            "OWNER"
          ],
          "type": "string"
        },
        "height": {
          "maximum": 99999,
          "type": [
            "null",
            "integer"
          ]
        },
        "thumbnail": {
          "format": "uri",
          "type": [
            "null",
            "string"
          ]
        },
        "type": {
          "maxLength": 4,
          "type": "string"
        },
        "url": {
          "format": "uri",
          "type": "string"
        },
        "width": {
          "maximum": 99999,
          "type": [
            "null",
            "integer"
          ]
        }
      },
      "required": [
        "url",
        "category",
        "type"
      ],
      "type": [
        "null",
        "object"
      ]
    },
    "Location": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "maxLength": 45,
          "type": "string"
        },
        "charging_when_closed": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "city": {
          "maxLength": 45,
          "type": "string"
        },
        "coordinates": {
          "$ref": "#/definitions/GeoLocation"
        },
        "country": {
          "maxLength": 3,
          "minLength": 3,
          "type": "string"
        },
        "directions": {
          "items": {
            "$ref": "#/definitions/DisplayText"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "energy_mix": {
          "anyOf": [
            {
              "$ref": "#/definitions/EnergyMix"
            },
            {
              "type": "null"
            }
          ]
        },
        "evses": {
          "items": {
            "$ref": "#/definitions/EVSE"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "facilities": {
          "items": {
            "$ref": "#/definitions/Facility"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "id": {
          "maxLength": 39,
          "type": "string"
        },
        "images": {
          "items": {
            "$ref": "#/definitions/Image"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "last_updated": {
          "format": "date-time",
          "type": "string"
        },
        "name": {
          "maxLength": 255,
          "type": [
            "null",
            "string"
          ]
        },
        "opening_times": {
          "anyOf": [
            {
              "$ref": "#/definitions/Hours"
            },
            {
              "type": "null"
            }
          ]
        },
        "operator": {
          "anyOf": [
            {
              "$ref": "#/definitions/BusinessDetails"
            },
            {
              "type": "null"
            }
          ]
        },
        "owner": {
          "anyOf": [
            {
              "$ref": "#/definitions/BusinessDetails"
            },
            {
              "type": "null"
            }
          ]
        },
        "postal_code": {
          "maxLength": 10,
          "type": "string"
        },
        "related_locations": {
          "items": {
            "$ref": "#/definitions/AdditionalGeoLocation"
          },
          "type": [
            "null",
            "array"
          ]
        },
        "suboperator": {
          "anyOf": [
            {
              "$ref": "#/definitions/BusinessDetails"
            },
            {
              "type": "null"
            }
          ]
        },
        "time_zone": {
          "maxLength": 255,
          "type": [
            "null",
            "string"
          ]
        },
        "type": {
          "$ref": "#/definitions/LocationType"
        }
      },
      "required": [
        "id",
        "type",
        "address",
        "city",
        "postal_code",
        "country",
        "coordinates",
        "last_updated"
      ],
      "type": "object"
    },
    "LocationType": {
      "enum": [
        "ON_STREET",
        "PARKING_GARAGE",
        "UNDERGROUND_GARAGE",
        "PARKING_LOT",
        "OTHER",
        "UNKNOWN"
      ],
      "type": "string"
    },
    "ParkingRestriction": {
      "enum": [
        "EV_ONLY",
        "PLUGGED",
        "DISABLED",
        "CUSTOMERS",
        "MOTORCYCLES"
      ],
      "type": "string"
    },
    "RegularHours": {
      "additionalProperties": false,
      "properties": {
        "period_begin": {
          "maxLength": 5,
          "minLength": 5,
          "pattern": "([0-1][0-9]|2[0-3]):[0-5][0-9]",
          "type": "string"
        },
        "period_end": {
          "maxLength": 5,
          "minLength": 5,
          "pattern": "([0-1][0-9]|2[0-3]):[0-5][0-9]",
          "type": "string"
        },
        "weekday": {
          "maximum": 7,
          "minimum": 1,
          "type": "integer"
        }
      },
      "required": [
        "weekday",
        "period_begin",
        "period_end"
      ],
      "type": "object"
    },
    "Status": {
      "enum": [
        "AVAILABLE",
        "BLOCKED",
        "CHARGING",
        "INOPERATIVE",
        "OUTOFORDER",
        "PLANNED",
        "REMOVED",
        "RESERVED",
        "UNKNOWN"
      ],
      "type": "string"
    },
    "StatusSchedule": {
      "additionalProperties": false,
      "properties": {
        "period_begin": {
          "format": "date-time",
          "type": "string"
        },
        "period_end": {
          "format": "date-time",
          "type": [
            "null",
            "string"
          ]
        },
        "status": {
          "enum": [
            "AVAILABLE",
            "BLOCKED",
            "CHARGING",
            "INOPERATIVE",
            "OUTOFORDER",
            "PLANNED",
            "REMOVED",
            "RESERVED",
            "UNKNOWN"
          ],
          "type": "string"
        }
      },
      "required": [
        "period_begin",
        "status"
      ],
      "type": "object"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/locations/2.1.1/valid/_examples/location.json
{
  "address": "F.Rooseveltlaan 3A",
  "city": "Gent",
  "coordinates": {
    "latitude": "51.047599",
    "longitude": "3.729944"
  },
  "country": "BEL",
  "evses": [
    {
      "capabilities": [
        "RESERVABLE"
      ],
      "connectors": [
        {
          "amperage": 16,
          "format": "CABLE",
          "id": "1",
          "last_updated": "2015-03-16T10:10:02Z",
          "power_type": "AC_3_PHASE",
          "standard": "IEC_62196_T2",
          "tariff_id": "11",
          "voltage": 220
        },
        {
          "amperage": 16,
          "format": "SOCKET",
          "id": "2",
          "last_updated": "2015-03-18T08:12:01Z",
          "power_type": "AC_3_PHASE",
          "standard": "IEC_62196_T2",
          "tariff_id": "11",
          "voltage": 220
        }
      ],
      "evse_id": "BE-BEC-E041503001",
      "floor_level": "-1",
      "last_updated": "2015-06-28T08:12:01Z",
      "physical_reference": "1",
      "status": "AVAILABLE",
      "status_schedule": [],
      "uid": "3256"
    },
    {
      "capabilities": [
        "RESERVABLE"
      ],
      "connectors": [
        {
          "amperage": 16,
          "format": "SOCKET",
          "id": "1",
          "last_updated": "2015-06-29T20:39:09Z",
          "power_type": "AC_3_PHASE",
          "standard": "IEC_62196_T2",
          "tariff_id": "12",
          "voltage": 220
        }
      ],
      "evse_id": "BE-BEC-E041503002",
      "floor_level": "-2",
      "last_updated": "2015-06-29T20:39:09Z",
      "physical_reference": "2",
      "status": "RESERVED",
      "uid": "3257"
    }
  ],
  "id": "LOC1",
  "last_updated": "2015-06-29T20:39:09Z",
  "name": "Gent Zuid",
  "operator": {
    "name": "BeCharged"
  },
  "postal_code": "9000",
  "type": "ON_STREET"
}
