=== johnknl/k6-ocpi/_data/schema/ocpi/tariffs/ocpi.2_2_1.tariffs.json
{
  "$ref": "#/definitions/ocpi.2_2_1.tariffs",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ocpi.2_2_1.tariffs": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "country_code": {
            "maxLength": 2,
            "minLength": 2,
            "type": "string"
          },
          "currency": {
            "maxLength": 3,
            "minLength": 3,
            "type": "string"
          },
          "elements": {
            "items": {
              "additionalProperties": false,
              "properties": {
                "price_components": {
                  "items": {
                    "additionalProperties": false,
                    "properties": {
                      "price": {
                        "minimum": 0,
                        "type": "number"
                      },
                      "step_size": {
                        "minimum": 0,
                        "type": "integer"
                      },
                      "type": {
                        "enum": [
                          "ENERGY",
                          "FLAT",
                          "PARKING_TIME",
                          "TIME"
                        ],
                        "type": "string"
                      },
                      "vat": {
                        "anyOf": [
                          {
                            "minimum": 0,
                            "type": "number"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      }
                    },
                    "required": [
                      "type",
                      "price",
                      "step_size"
                    ],
                    "type": "object"
                  },
                  "minItems": 1,
                  "type": "array"
                },
                "restrictions": {
                  "anyOf": [
                    {
                      "additionalProperties": false,
                      "properties": {
                        "day_of_week": {
                          "anyOf": [
                            {
                              "items": {
                                "enum": [
                                  "MONDAY",
                                  "TUESDAY",
                                  "WEDNESDAY",
                                  "THURSDAY",
                                  "FRIDAY",
                                  "SATURDAY",
                                  "SUNDAY"
                                ],
                                "type": "string"
                              },
                              "type": "array"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "end_date": {
                          "anyOf": [
                            {
                              "maxLength": 10,
                              "minLength": 10,
                              "pattern": "([12][0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])",
                              "type": "string"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "end_time": {
                          "anyOf": [
                            {
                              "maxLength": 5,
                              "minLength": 5,
                              "pattern": "([0-1][0-9]|2[0-3]):[0-5][0-9]",
                              "type": "string"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "max_current": {
                          "anyOf": [
                            {
                              "minimum": 0,
                              "type": "number"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "max_duration": {
                          "anyOf": [
                            {
                              "minimum": 0,
                              "type": "integer"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "max_kwh": {
                          "anyOf": [
                            {
                              "minimum": 0,
                              "type": "number"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "max_power": {
                          "anyOf": [
                            {
                              "minimum": 0,
                              "type": "number"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "min_current": {
                          "anyOf": [
                            {
                              "minimum": 0,
                              "type": "number"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "min_duration": {
                          "anyOf": [
                            {
                              "minimum": 0,
                              "type": "integer"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "min_kwh": {
                          "anyOf": [
                            {
                              "minimum": 0,
                              "type": "number"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "min_power": {
                          "anyOf": [
                            {
                              "minimum": 0,
                              "type": "number"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "reservation": {
                          "anyOf": [
                            {
                              "enum": [
                                "RESERVATION",
                                "RESERVATION_EXPIRES"
                              ],
                              "type": "string"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "start_date": {
                          "anyOf": [
                            {
                              "maxLength": 10,
                              "minLength": 10,
                              "pattern": "([12][0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])",
                              "type": "string"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "start_time": {
                          "anyOf": [
                            {
                              "maxLength": 5,
                              "minLength": 5,
                              "pattern": "([0-1][0-9]|2[0-3]):[0-5][0-9]",
                              "type": "string"
                            },
                            {
                              "type": "null"
                            }
                          ]
                        }
                      },
                      "type": "object"
                    },
                    {
                      "type": "null"
                    }
                  ]
                }
              },
              "required": [
                "price_components"
              ],
              "type": "object"
            },
            "minItems": 1,
            "type": "array"
          },
          "end_date_time": {
            "anyOf": [
              {
                "format": "date-time",
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "energy_mix": {
            "anyOf": [
              {
                "additionalProperties": false,
                "properties": {
                  "energy_product_name": {
                    "anyOf": [
                      {
                        "maxLength": 64,
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "energy_sources": {
                    "anyOf": [
                      {
                        "items": {
                          "additionalProperties": false,
                          "properties": {
                            "percentage": {
                              "maximum": 100,
                              "minimum": 0,
                              "type": "number"
                            },
                            "source": {
                              "enum": [
                                "NUCLEAR",
                                "GENERAL_FOSSIL",
                                "COAL",
                                "GAS",
                                "GENERAL_GREEN",
                                "SOLAR",
                                "WIND",
                                "WATER"
                              ],
                              "type": "string"
                            }
                          },
                          "required": [
                            "source",
                            "percentage"
                          ],
                          "type": "object"
                        },
                        "type": "array"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "environ_impact": {
                    "anyOf": [
                      {
                        "items": {
                          "additionalProperties": false,
                          "properties": {
                            "amount": {
                              "type": "number"
                            },
                            "source": {
                              "enum": [
                                "NUCLEAR_WASTE",
                                "CARBON_DIOXIDE"
                              ],
                              "type": "string"
                            }
                          },
                          "required": [
                            "source",
                            "amount"
                          ],
                          "type": "object"
                        },
                        "type": "array"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "is_green_energy": {
                    "type": "boolean"
                  },
                  "supplier_name": {
                    "anyOf": [
                      {
                        "maxLength": 64,
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "is_green_energy"
                ],
                "type": "object"
              },
              {
                "type": "null"
              }
            ]
          },
          "id": {
            "maxLength": 36,
            "type": "string"
          },
          "last_updated": {
            "format": "date-time",
            "type": "string"
          },
          "max_price": {
            "anyOf": [
              {
                "$ref": "#/definitions/ocpi.2_2_1.tariffs/items/properties/min_price/anyOf/0"
              },
              {
                "type": "null"
              }
            ]
          },
          "min_price": {
            "anyOf": [
              {
                "additionalProperties": false,
                "properties": {
                  "excl_vat": {
                    "minimum": 0,
                    "type": "number"
                  },
                  "incl_vat": {
                    "anyOf": [
                      {
                        "minimum": 0,
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "excl_vat"
                ],
                "type": "object"
              },
              {
                "type": "null"
              }
            ]
          },
          "party_id": {
            "maxLength": 3,
            "type": "string"
          },
          "start_date_time": {
            "anyOf": [
              {
                "format": "date-time",
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "tariff_alt_text": {
            "anyOf": [
              {
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "language": {
                      "maxLength": 2,
                      "minLength": 2,
                      "type": "string"
                    },
                    "text": {
                      "maxLength": 512,
                      "type": "string"
                    }
                  },
                  "required": [
                    "language",
                    "text"
                  ],
                  "type": "object"
                },
                "type": "array"
              },
              {
                "type": "null"
              }
            ]
          },
          "tariff_alt_url": {
            "anyOf": [
              {
                "format": "uri",
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "type": {
            "anyOf": [
              {
                "enum": [
                  "AD_HOC_PAYMENT",
                  "PROFILE_CHEAP",
                  "PROFILE_FAST",
                  "PROFILE_GREEN",
                  "REGULAR"
                ],
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "id",
          "country_code",
          "party_id",
          "currency",
          "elements",
          "last_updated"
        ],
        "type": "object"
      },
      "type": "array"
    }
  }
}

=== johnknl/k6-ocpi/_data/examples/tariffs/2.2.1/valid/_examples/tariff.json
{
  "country_code": "DE",
  "currency": "EUR",
  "elements": [
    {
      "price_components": [
        {
          "price": 2,
          "step_size": 300,
          "type": "TIME",
          "vat": 10
        }
      ]
    }
  ],
  "id": "12",
  "last_updated": "2024-05-31T00:00:00Z",
  "party_id": "ALL"
}
